# Pull the Node image from Docker Hub
FROM node:14-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json and package-lock.json (if available)
COPY frontend/package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

# Your app binds to port 3000, so you'll use the EXPOSE instruction to have it mapped by the docker daemon
EXPOSE 3000

# Run the React app
CMD ["npm", "start"]
